- name: Install Emby
  package:
    state: present
    name:
    - "emby-server"
  when: ansible_facts['distribution'] == "Archlinux"
  tags:
  - media_server

- name: Start and enable Emby
  service:
    name: emby-server
    state: started
    enabled: yes
  when: ansible_facts['distribution'] == "Archlinux"
  tags:
  - media_server

- name: Add emby user to groups
  user:
    name: emby
    group: emby
    groups:
    - emby
    - jiri
  when: ansible_facts['distribution'] == "Archlinux"
  tags:
  - media_server
